### ISSUE TITLE
Tests failing in fragmentation runs

### ISSUE THREAD

**Issue by mayankgupta804** [testvagrant/optimusTemplate#1]
If the tests are, due to some reason, stopped during a fragmentation run, and then again when the tests are run from the beginning, an error is thrown saying that the tests failed.This could possibly due to failure in the proper shutdown of the Redis server.However, if we do a Gradle run, the error does not occur.In fact, after the Gradle run, if we do a proper test run, the error does not occur at all.
Below, the image is attached which is related to the problem being faced.
![image](https://cloud.githubusercontent.com/assets/18723451/25649106/3e769a7a-2ff0-11e7-9a72-d687d61ecb27.png)

**Comment by KrishnB** [comment]
This issue will be resolved as part of Optimus 2.0 As a workaround you can run `optimusSetup` task before executing scenarios form IDE. Also please pass `-DtestFeed=<yourtestfeedname>     -DrunMode=Fragmentation` to your scenario VM options. You can learn more about setting default vm options [here](https://www.jetbrains.com/help/idea/2017.1/creating-and-editing-run-debug-configurations.html)

**Comment by KrishnB** [comment]
Resolved this issue in Optimus 2.0. Please refer [here](https://github.com/testvagrant/optimusTemplate/wiki/Migrating-to-Optimus-2.0) for migrating to Optimus 2.0
