### ISSUE TITLE
Question: iOS - Need more details on how we can run an application which is already installed

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#10]
First of all thanks a lot for developing such a nice project. It makes the life real easy to test mobile application.

I have few queries, i tried searching all documents but did not find enough information.

1: If I want to run already installed application , how can i do that ? As the framework need .apk or app to be present in /app folder ? Is there any way i can override the settings ?

e.g In one of my iPhone the application is already installed i want to run it without reinstalling .

Like in Appium capability we can 

        capabilities.setCapability("noReset", true);
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("bundleId","com.XYZ.dev.abc");
This will only open the app in the device rather installation.

Thanks a lot for your help and support.

**Comment by KrishnB** [comment]
@asitishere you can pass any number of capabilities through your test feed. For the above capabilities you can modify your testfeed as below
```{
  "executionDetails": {
    "appium_js_path": "/usr/local/bin/appium",
    "appium_node_path": "/usr/local/bin/node"
  },
  "testFeed":[
    {
      "belongsTo":"user",
      "runsOn": "any",
      "appDir": "app",
      "nativeApp":true,
      "optimusDesiredCapabilities": {
        "appiumServerCapabilities": {
          "app": "HelloOptimus.app",
          "platformName": "Ios"
        },
        "iosOnlyCapabilities": {
          "bundleId": "com.XYZ.dev.abc",
          "noReset":true,
          "fullReset":false
        }
      }
    }
  ]
}

Any capability can be passed through your respective testfeed.

**Comment by asitishere** [comment]
Thanks Krishna, will check and let you know

**Comment by asitishere** [comment]
Hi Krishan .....

if i will replace app with .ipa will that work ???

  "executionDetails": {
    "appium_js_path": "/usr/local/bin/appium",
    "appium_node_path": "/usr/local/bin/node"
  },
  "testFeed":[
    {
      "belongsTo":"user",
      "runsOn": "any",
      "appDir": "app",
      "nativeApp":true,
      "optimusDesiredCapabilities": {
        "appiumServerCapabilities": {
          "app": "HelloOptimus.ipa",
          "platformName": "Ios"
        },
        "iosOnlyCapabilities": {
          "bundleId": "com.XYZ.dev.abc",
          "noReset":true,
          "fullReset":false
        }
      }
    }
  ]
}

**Comment by asitishere** [comment]
thanks...worked like a champ.
