### ISSUE TITLE
Run/Debug feature file from intellij not working.

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#15]
I followed the wiki: https://github.com/testvagrant/optimusTemplate/wiki/How-to-run-features-from-intellij

scenario runner need Feature file Location, Module and Main class to start cucumber feature. I am attaching the screen short, I hope the Gradle task for the project remains “optimusSetup”

Please suggest what I am missing, without debug life is rocky.
<img width="520" alt="screen shot 2017-10-24 at 2 51 43 pm" src="https://user-images.githubusercontent.com/7847381/31924666-cf9f188a-b8ce-11e7-813f-a84cb90eca5b.png">

Regards
Asit

**Comment by asitishere** [comment]
Once fixed please share the detailed steps.

**Comment by sukesh15** [comment]
The problem seems to be with the Gherkin version you are using. Update to latest gherkin version and it should work. Also, there was a slight change needed in wiki (an extra step where you need to add a VM param for optimusSetup gradle task), that has been fixed. Let us know when it works for you.

**Comment by sukesh15** [comment]
Jetbrains plugin repository shows 2 results when you search for Gherkin. You need to pick up the latest here [https://plugins.jetbrains.com/plugin/9164-gherkin](url)

**Comment by asitishere** [comment]
Thanks for extended help and support Sukesh.
Closing the Issue as its working now .
