### ISSUE TITLE
Debug mode points to wrong device while connecting multiple devices with appiumServerCapability has "UUID" and "deviceName" specified.

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#19]
Note: Please attach 2 devices to the system where we are debugging with the application installed.

    {
      "belongsTo": "XXX",
      "runsOn": "device",
      "appDir": "app",
      "nativeApp":true,
      "optimusDesiredCapabilities": {
        "appiumServerCapabilities": {
          "app": "UIRefresh.ipa",
          "platformName": "iOS",
          "automationName": "XCUITest",
          "udid":"b31c1ad0774e4b366ac5e4286357a1957df19ab3",
          "deviceName":"iPhone8Auto"
       } 

Add a breakpoint and start debugging.

Expected: As we already provided uuid and device name the debug should point to specific device. 
Actual: App start in another device and not point to device details specified under server capability.

This is not something blocking but good to have a look .

**Comment by sukesh15** [comment]
@asitishere Have your tried it recently, is it still happening for you with later versions.
