### ISSUE TITLE
Queries: appium driver, server, parallel execution

### ISSUE THREAD

**Issue by vikramvi** [testvagrant/optimusTemplate#2]
Hi,

Please clarify below
- how & which file does creation of android/ios driver, 
- launch server how it takes place
- can I pass any additional flags if needed e.g. local time zone etc
- how do you achieve parallel execution.
- where do you specify appium java client version ?
- overview of technical implementation of the framework can be useful for those who want to dig deep and contribute 

I tried searching the repo but didn't find answers 

Thanks & Regards,
Vikram

**Comment by sukesh15** [comment]
Hi Vikram,

The answer to majority of your questions is optimus jar that the template project is dependent on. You would have seen that in the gradle dependencies. Currently the source code for optimus is in a private repo as we are in the process of cleaning it up a little before making it public on github. Should be out in a week or so. Not only optimus, there are a bunch of other related projects that will be made public:

- Stepdefs - that takes care of common vocabulary for writing specs
- mdb - a wrapper interface for android and iOS commands
- optimus-commons - a common library used for optimus and related project

Meanwhile, here is a brief architecture diagram that you can refer to understand what's going behind the scene.

![image](https://user-images.githubusercontent.com/2215667/28618752-21fe2af0-7223-11e7-8d47-279cc75edc92.png)

**Comment by vikramvi** [comment]
Thanks @sukesh15 for detailed info. I will wait for other repos to be public in few days.

As I'm also investing time in doing similar things, would like to put joint efforts instead of working on similar problems separately.

Regards,
Vikram

**Comment by vikramvi** [comment]
@sukesh15 

1. Please let me know by when you are planning to open source **source code for optimus** ?

2. wrt your post https://discuss.appium.io/t/alternative-to-selenium-grid-for-running-appium-tests-in-parallel/18025
2.1 what does you mean by "...these devices, distributed or fragmented"

3. Does optimus framework takes care of below
3.1 assigning test cases to available nodes at run time ?
3.2 OR it creates test runner for each of the test classes / feature file and assign to each of the nodes ?

I'm as well trying to solve same problems at my end, but it will good to put minds together on single framework, instead of working separately :)

Thanks,
Vikram

**Comment by sukesh15** [comment]
@vikramvi 

We are almost there, all the code should get published latest by mid next week. Will keep the group posted.

With respect to running tests in parallel, we have seen teams asking for either or both of the following ways:

- **Distributed** - where you distribute your test load across devices. e.g. you have 50 tests and you want a faster feedback by distributing them on more than one connected devices. At the moment, optimus allows distribution at feature level. Each device thread running one feature file at a time. What that also means is, the fastest your tests finish depend on the longest running feature file.
- **Fragmented** - where you want to run all tests on all devices. e.g. you have 50 tests and you want to run all 50 on each one of your connected devices. The idea here is more to check device level coverage of every single feature.

Having said this, optimus allows doing both of the above as a pre-configured task. You just need to connect devices and choose to run the task that you need.

**Optimus assignment of tests:**

1. Firstly, using optimus every tests runs in its own container. So every test has its own appium server instance and driver instance that is created dynamically at run time. The number of test run threads are created based on number of connected and configured devices.

2. Now about assignment of test:
- [ ]  In case of distributed, a test just picks up the first available device in the pool (maintained in MongoDb) and creates the driver instance at run time with corresponding device details. 
- [ ]  In case of fragmented, optimus binds devices to separate threads and every thread would then run all tests.

**Comment by vikramvi** [comment]
@sukesh15 thanks again for detailed info. 
Once source code repo is live, I will submit PR for documentation ( Q&A ) with above clarifications from you.   As it'll be very useful to others as well.

**Comment by sukesh15** [comment]
@vikramvi and everyone else following up on this, thanks a lot for all your patience. We have published all the repos on our testvagrant github page [here](https://github.com/testvagrant/), a total of 8 repositories. We have consciously tried to follow a decentralised approach in terms of the whole structuring of the code.

Also, attaching a diagram to briefly explain how the projects are grouped and their responsibility.
Feel free to reach out in case of any questions/clarifications/feedback/suggestions. 


![optimus template](https://user-images.githubusercontent.com/2215667/29169155-2fa88406-7df0-11e7-9a84-217d1d799fae.png)

**Comment by vikramvi** [comment]
@sukesh15 Thanks a ton for sharing this info, I will go through it and get back in case of any doubts.
