### ISSUE TITLE
Building is failing

### ISSUE THREAD

**Issue by sampadrout** [testvagrant/optimusTemplate#3]
Hi,
First of all thanks for developing such a beautiful framework for mobile automation. Its always a challenge to put all sorts of technologies to make a stable mobile test automation solution. out of curiosity, i was trying this today and getting the following error. It will be great if you can suggest me the fix for this. Thanks. Sampad.
Here i am running this for android.
gradle runFragmentation -DtestFeed=HelloOptimusAndroid -Dtags=@helloOptimus

> Task :compileTestJava
Note: /Users/sampadrout/AMA_New/src/test/java/pages/BasePage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runFragmentation
Executing MongoMain

> Task :fragmentationReport
MongoClient:1681325373

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runFragmentation'.
> Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':fragmentationReport'.
> Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED in 6m 24s
7 actionable tasks: 7 executed

**Comment by sampadrout** [comment]
Please ignore above comments. I have fixed the monogodb connection issues. Its working great. Thanks

**Comment by KrishnB** [comment]
@sampadrout looks like MongoDB has failed to start within the expected time. 

Please follow below steps for a resolution.

#### Step 1: Open a new terminal and run `mongod` command.
#### Step 2: Check if it throws any error related to this `exception in initAndListen: 29 Data directory /data/db not found., terminating`. 
#### Step 3: If you find error as mentioned in step2, please follow this link to resolve it https://github.com/testvagrant/optimusTemplate/wiki/FAQ#faq6 
#### Step 4: Once resolved, run `mongod` command again in terminal. A mongo instance should be up and running on `27017` port. 
#### Step 5: Run the task `gradle runFragmentation -DtestFeed=HelloOptimusAndroid -Dtags=@helloOptimus`
