### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Cannot parse object because no supported Content-Type was specified in response. Content-Type was 'text/html;charset=iso-8859-1'.

### ISSUE THREAD

**Issue by asitishere** [testvagrant/optimusTemplate#31]
10:39:28 Mongo uri mongodb://localhost:27017
10:39:28 Services URI http://localhost:8080/v1
10:39:28 Service commands [java, -jar, /Users/jenkins/.jenkins/workspace/MobileApp(Android)/libs/optimus-services-1.0.jar, --port=8080, --database=optimus, --uri=mongodb://localhost:27017]
10:44:31 :runFragmentation
10:44:32 Notifying build start
10:44:32 Builds Pathhttp://localhost:8080/v1/builds
10:44:34 Exception in thread "main" java.lang.IllegalStateException: Cannot parse object because no supported Content-Type was specified in response. Content-Type was 'text/html;charset=iso-8859-1'.
10:44:34 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:44:34 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:44:34 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:44:34 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:44:34 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
10:44:34 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
10:44:34 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
10:44:34 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
10:44:34 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
10:44:34 	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:82)
10:44:34 	at io.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
10:44:34 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
10:44:34 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
10:44:34 	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:222)
10:44:34 	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:164)
10:44:34 	at com.testvagrant.monitor.clients.BuildsClient.createNewBuild(BuildsClient.java:25)
10:44:34 	at com.testvagrant.monitor.services.BuildsServiceImpl.notifyBuildStart(BuildsServiceImpl.java:21)
10:44:34 	at com.testvagrant.monitor.MongoMain.createOptimusDb(MongoMain.java:54)
10:44:34 	at com.testvagrant.optimus.OptimusMain.setup(OptimusMain.java:37)
10:44:34 	at com.testvagrant.optimus.OptimusMain.main(OptimusMain.java:33)
10:44:34 /Users/jenkins/.jenkins/workspace/MobileApp(Android)/src/test/resources/ProdAndroid.json
10:44:35 :runFragmentation FAILED
10:44:35 :fragmentationReport
10:44:35 updating build end time
10:44:35 java.lang.IllegalStateException: Cannot parse object because no supported Content-Type was specified in response. Content-Type was 'text/html;charset=utf-8'.
10:44:35 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:44:35 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:44:35 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:44:35 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:44:35 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
10:44:35 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
10:44:35 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
10:44:35 	at io.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:82)
10:44:35 	at io.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
10:44:35 	at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:222)
10:44:35 	at io.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:164)
10:44:35 	at com.testvagrant.monitor.clients.BuildsClient.getLatestBuildId(BuildsClient.java:40)
10:44:35 	at com.testvagrant.monitor.services.OptimusServiceImpl.getLatestBuild(OptimusServiceImpl.java:10)
10:44:35 	at com.testvagrant.monitor.services.BuildsServiceImpl.notifyBuildEnd(BuildsServiceImpl.java:26)
10:44:35 	at com.testvagrant.monitor.services.BuildsService$notifyBuildEnd.call(Unknown Source)
10:44:35 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
10:44:35 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
10:44:35 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
10:44:35 	at com.testvagrant.optimus.utils.OptimusTearDown.updateBuildRecord(OptimusTearDown.groovy:9)
10:44:35 	at com.testvagrant.optimus.utils.OptimusTearDown$updateBuildRecord.call(Unknown Source)
10:44:35 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
10:44:35 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
10:44:35 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
10:44:35 	at com.testvagrant.optimus.tasks.FragmentationReportTask.fragmentationReport(FragmentationReportTask.groovy:20)
10:44:35 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:44:35 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:44:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:44:35 	at java.lang.reflect.Method.invoke(Method.java:498)
10:44:35 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
10:44:35 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
10:44:35 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
10:44:35 	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
10:44:35 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:692)
10:44:35 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:675)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
10:44:35 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
10:44:35 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
10:44:35 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
10:44:35 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
10:44:35 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
10:44:35 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
10:44:35 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
10:44:35 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
10:44:35 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
10:44:35 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
10:44:35 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
10:44:35 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
10:44:35 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
10:44:35 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
10:44:35 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
10:44:35 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
10:44:35 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
10:44:35 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
10:44:35 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
10:44:35 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
10:44:35 	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:230)
10:44:35 	at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:227)
10:44:35 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
10:44:35 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
10:44:35 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:161)
10:44:35 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
10:44:35 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
10:44:35 	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
10:44:35 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
10:44:35 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
10:44:35 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
10:44:35 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
10:44:35 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
10:44:35 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
10:44:35 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
10:44:35 	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
10:44:35 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
10:44:35 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
10:44:35 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
10:44:35 	at org.gradle.util.Swapper.swap(Swapper.java:38)
10:44:35 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
10:44:35 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
10:44:35 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
10:44:35 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
10:44:35 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
10:44:35 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
10:44:35 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
10:44:35 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
10:44:35 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:44:35 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:44:35 	at java.lang.Thread.run(Thread.java:748)
10:44:35 Parsing report
10:44:35 ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
10:44:35 
10:44:35 R

**Comment by asitishere** [comment]
Not an issue ...just a config change if port is used.

**Comment by MohsinWaqas31** [comment]
what it the change. please let me know
