### ISSUE TITLE
Getting error  "Unable to start WebDriverAgent session because of xcodebuild failure:" if run scripts together in a suite. 

### ISSUE THREAD

**Issue by Jaspreet23** [testvagrant/optimusTemplate#37]
Hello,

My scripts work fine if I run them individually but if I am running these in a suite using tags, it fails due to the issue with WebDriverException error.

I am running scripts with command line
 ./gradlew runFragmentation -DtestFeed=iOS-qa -Dtags=@run

**ISSUE:**
org.openqa.selenium.WebDriverException: It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'nsur01mac028', ip: 'fe80:0:0:0:103d:f95b:dcb3:d71f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_181'
Driver info: driver.version: IOSDriver

**Environment**
Appium version (or git revision) that exhibits the issue: 1.9.1
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.13.6
Node.js version (unless using Appium.app|exe):v10.10.0
Mobile platform/version under test: IPhone 8 plus (12.1)
Real device or emulator/simulator: Real
Appium CLI or Appium.app|exe: CLI and exe both

Is this an issue with how we are initiating the web driver agent? Kindly help!!

**Comment by thenishant** [comment]
This means that java client cannot connect to the server because it does not listen on the given host/port. Make sure the server is listening there first, for example with `netstat` tool.

**Comment by thenishant** [comment]
@Jaspreet23 Can you provide complete logs for this issue.

**Comment by JasWoolieX** [comment]
Hello @nishantverma This issue got resolved for me. Thanks.

**Comment by thenishant** [comment]
hey, @JasWoolieX can you let us know how did you fix this and then close this issue with the solution.

**Comment by JasWoolieX** [comment]
Hello @thenishant,
From what I remember I resolved by downgrading my appium version to a beta version. I will get back to you if I can get more details but mostly it was around appium version not being compatible.

**Comment by thenishant** [comment]
Closing as fixed by downgrading the Appium version to beta
