### ISSUE TITLE
is possible run test withoup app capabilites?

### ISSUE THREAD

**Issue by pgtoopx** [testvagrant/optimusTemplate#41]
Hello, I wanted to know if there is the possibility of doing the test without passing the application, nor the appdir to the feed.

**Comment by thenishant** [comment]
Hey @pgtoopx 
So there are two ways to run the app on mobile
1. Have the app preinstall and don't use *app* capability( cannot use a newer version, same build has to used every time) but appPackage and appActivity.
2. Or have the appdir in your feed and use it.
