### ISSUE TITLE
Question:  In the report for the completed tests is there a way that we can Custom name the device UDID?

### ISSUE THREAD

**Issue by Balhindi** [testvagrant/optimusTemplate#45]
![Untitled](https://user-images.githubusercontent.com/17076818/58046134-78edf800-7b12-11e9-94cd-ef0210284b26.png)

In here I want to see if I can change that Device name to something more readable? For example one of the devices is connected to a debug board and uses the IP address 192.168.1.100 and instead of calling it that it just says "Emulator_100".

Thank you.

**Comment by KrishnB** [comment]
This was done for readability purpose, we had masked ip address with custom name

**Comment by KrishnB** [comment]
_100 is taken from 192.168.1.100.

**Comment by Balhindi** [comment]
Can you point me to the Class that is in Optimus where I can choose if I want a custom name added? Thank you.
