### ISSUE TITLE
Question:Android I have devices that I want connected to the host, but don't tests to run on it how do I acheive this

### ISSUE THREAD

**Issue by Balhindi** [testvagrant/optimusTemplate#47]
sorry last question.

I am doing some tests where I am pairing the device via Bluetooth to another ADB device that is running the original test. Is there a way to stop or exclude one device from running the original test?

Thank you.

**Comment by KrishnB** [comment]
We cannot exclude a specific device but you can run your tests with below filters in place
* By passing UDID - Tests will run only on that device
* By passing device type, Device/Emulators/Simulator - Tests will run only on that type
* By passing O.S version - Tests will run on a specific version.

Please try with one of these filters that can exclude your device.

**Comment by Balhindi** [comment]
I added in my before step by passing a UDID to "device" String and said if(device.equals.("Xdevice"){System.exit("0");

but the tests are still running on that particular device. Any ideas on the correct way to do this?

Thank you.

**Comment by Balhindi** [comment]
Please help, I want to use this Framework, but I will be using something else if I can't get a good answer on how to disconnect phones based on UDID, I tried a System Exit, and it still tried to do the test on the phone.

Any ideas?

Thank you.

**Comment by KrishnB** [comment]
Hi, sadly we don't support this feature yet and is not a general use case for Optimus. I fear we may not able to help you at this point of time. Do let us know if we can help you further.
