### ISSUE TITLE
Question: Running tests parallel on both the platforms at the same time

### ISSUE THREAD

**Issue by suhasini-Ravi** [testvagrant/optimusTemplate#50]
Hi Team,

Thank you for the framework which is currently running parallel on the iOS and Android independently.

My requirement is to run the tests parallel on both iOS and Android at the same tinme using a single testfeed.

Could you please let me know is this feature is available currently, and if available could you help me in achieving.

**Comment by thenishant** [comment]
Hey @suhasini-Ravi 
Running tests parallel on both the platforms at the same time via a `single Testfeed` is not supported as now.

You can only specify one type of Platform either `Android` or `iOS` within a single file.

**Comment by suhasini-Ravi** [comment]
Hi @thenishant 

Thank you for your prompt response. Is there any chance to support for the feature in the next or future releases of Optimus.

**Comment by thenishant** [comment]
I don't think we have this in our roadmap at least for next release few releases, as this is directly dependent on appium. 
You cannot have two `platformName` key with multiple values.
Maybe we will work on this.

**Comment by suhasini-Ravi** [comment]
Thank you...
