### ISSUE TITLE
Kindly produce a documentation on how to produce the fragmentation test runner in multiple devices..

### ISSUE THREAD

**Issue by adityabhargav** [testvagrant/optimusTemplate#52]

**Comment by thenishant** [comment]
Step 1: Connect devices(Android or IOs) or create an Android Emulator.
Step 2: Open your favourite terminal and navigate to the project folder.
Step 3: Check for Android Devices or Emulators by running
Run this command -> `gradle runFragmentation -DtestFeed=<Your test feed file> -Dtags=@<your tag>`

There is no specific documentation to run tests on fragmentation mode... It's just a single command.
