### ISSUE TITLE
iOS - cannot run tests on iPhone XR

### ISSUE THREAD

**Issue by sandeepmosali23** [testvagrant/optimusTemplate#55]
I am unable to run tests on iPhone xr (only) but able to run tests on other iOS devices.

**Error details:**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runFragmentation'.
> com.testvagrant.commons.exceptions.DeviceMatchingException: No devices found running on DEVICE, check if you have DEVICEs connected

Any idea what would have happend?

**Comment by vinaykumarvvs** [comment]
Hi @sandeepmosali23 could you please confirm whether the device is listing or not when you execute this `xcrun instruments -s devices` command in terminal.

**Comment by sandeepmosali23** [comment]
@vinaykumarvvs when i run `xcrun instruments -s devices ` device is listed on the terminal

**Comment by vinaykumarvvs** [comment]
ok @sandeepmosali23. Thanks for confirming. Will check and let you know.

**Comment by vinaykumarvvs** [comment]
@sandeepmosali23 Looks like there is an issue with the UDID. The UDID for older devices is 40 characters long and for new iPhone devices, it is 25. I'm suspecting this is the reason why the device is not identified/picked for the automation.

**Comment by vinaykumarvvs** [comment]
@sandeepmosali23 meanwhile could you please try this https://github.com/appium/appium/issues/11448#issuecomment-427524554 and let us know whether it is fixed or not.

**Comment by sandeepmosali23** [comment]
@vinaykumarvvs above mentioned issue was closed last year( latest comment is not related issue im facing). Also i was able to launch app and find locators using appium UI.

**Comment by vinaykumarvvs** [comment]
@sandeepmosali23 ok we will look into the issue and get back to you. Thanks for raising it.

**Comment by sandeepmosali23** [comment]
@vinaykumarvvs any update on this issue?

**Comment by vinaykumarvvs** [comment]
@KrishnB could you please follow up on this issue.

**Comment by thenishant** [comment]
Hey @sandeepmosali23 
this has been fixed in the latest release of optimus.
https://github.com/testvagrant/optimus/releases/tag/v3.1.3
