### ISSUE TITLE
Unable to install - optimus-cli with node v9.0.0

### ISSUE THREAD

**Issue by NitinKanawalli** [testvagrant/optimusTemplate#57]
I am getting errors while trying to install the optimus-cli

details of the CLI:

**$ nvm list**
->       v9.0.0
       v10.15.0
       v10.15.3
       v12.13.1
         system
default -> 10.15.0 (-> v10.15.0)
node -> stable (-> v12.13.1) (default)
stable -> 12.13 (-> v12.13.1) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.19.0 (-> N/A)
lts/erbium -> v12.16.0 (-> N/A)
**$ nvm use v9.0.0**
Now using node v9.0.0 (npm v5.5.1)
**$ npm install -g optimus-cli**
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/bin/optimus -> /Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/index.js

> nodegit@0.24.3 install /Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.24.3 and node@9.0.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error socket hang up

gyp
WARN
install got an error, rolling back install
gyp
ERR! configure error
gyp ERR!
stack Error: socket hang up
gyp ERR!
stack     at TLSSocket.onConnectEnd (_tls_wrap.js:1069:19)
gyp ERR!
stack     at Object.onceWrapper (events.js:322:30)
gyp ERR!
stack     at emitNone (events.js:120:20)
gyp ERR!
stack     at TLSSocket.emit (events.js:218:7)
gyp
ERR! stack     at endReadableNT (_stream_readable.js:1054:12)
gyp
ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
gyp ERR!
System Darwin 18.0.0
gyp
ERR! command "/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/bin/node" "/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release" "--node_abi_napi=node-v59" "--napi_build_version=0" "--node_napi_label=node-v59"
gyp ERR! cwd
/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit
gyp ERR!
node -v v9.0.0
gyp
ERR! node-gyp -v v4.0.0
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp
ERR! stack Error: Failed to execute '/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/bin/node /Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release --node_abi_napi=node-v59 --napi_build_version=0 --node_napi_label=node-v59' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp
ERR!
stack     at emitTwo (events.js:135:13)
node-pre-gyp
ERR! stack
at ChildProcess.emit (events.js:224:7)
node-pre-gyp
ERR!
stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp
ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR!
System Darwin 18.0.0
node-pre-gyp ERR! command "/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/bin/node" "/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp
ERR! cwd /Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit
node-pre-gyp
ERR! node -v v9.0.0
node-pre-gyp ERR!
node-pre-gyp -v v0.11.0
node-pre-gyp
ERR! not ok
Failed to execute '/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/bin/node /Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/nitinkanawalli/.nvm/versions/node/v9.0.0/lib/node_modules/optimus-cli/node_modules/nodegit/build/Release --node_abi_napi=node-v59 --napi_build_version=0 --node_napi_label=node-v59' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN ngclipboard@2.0.0 requires a peer of angular@^1.2.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.24.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.24.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nitinkanawalli/.npm/_logs/2020-02-17T03_21_53_171Z-debug.log
Nitins-MBP:~ nitinkanawalli$

**Comment by thenishant** [comment]
Hey @NitinKanawalli 
Optimus-cli currently supports node version 8.4.0

You need to downgrade it to node v8.

**Comment by NitinKanawalli** [comment]
@thenishant , Yeah i was ale to resolve this with - v8.11.1, but still mongodb is not getting installed

**Comment by thenishant** [comment]
Formula MongoDB has been removed from homebrew-core. Check pr-43770 from homebrew-core

Try install installing MongoDB community edition.

```brew services stop mongodb
brew uninstall mongodb

brew tap mongodb/brew
brew install mongodb-community
brew services start mongodb-community

**Comment by NitinKanawalli** [comment]
@thenishant Thanks... it worked... appreciate your quick response. Is it documented??

**Comment by thenishant** [comment]
No not yet

**Comment by falermus81** [comment]
Hi, I try to downgrade to Node 8, but it is not available anymore. My Node now is 14. Is it still not compatible with Optimus?

**Comment by thenishant** [comment]
It is still available. Try searching the official node website

**Comment by falermus81** [comment]
Yes, it available on the website, but I cannot search it using brew. Only version 10 and 12 available using brew way

**Comment by KrishnB** [comment]
@falermus81 if you are getting started with Optimus for the first time, suggest you try the latest one here => https://optimus.now.sh/docs/getting-started.
